# Hugo Paper theme

name = "Paper"
license = "MIT"
licenselink = "https://github.com/lsuhadolnik/hugo-paper/blob/master/LICENSE"
description = "A simple, cleam, one-column template"
homepage = "https://github.com/lsuhadolnik/hugo-paper/"
tags = ["Responsive", "Simple", "Clean", "Light", "White", "Blog"]
features = ["Responsive", "One Column", "Blog"]
min_version = "0.1"

[author]
  name = "21beats"
  homepage = "http://21beats.com/"

# If porting an existing theme
[original]
  name = "21beats"
  homepage = "http://21beats.com/"
  repo = "https://github.com/nanxiaobei/hugo-paper/"
